modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"
issueTrackerURL="https://github.com/BNDS-tx/Changed-Minecraft-Mod/issues" #optional

[[mods]]
modId="changed"
version="0.14.1c.t"
displayName="Changed: Minecraft Mod Modified by Azurebyss"
updateJSONURL="https://raw.githubusercontent.com/BNDS-tx/Changed-Minecraft-Mod/master/update.json"
displayURL="https://github.com/BNDS-tx/Changed-Minecraft-Mod/blob/1.18.2-dev/README.md"
logoFile="icon@400.png"
credits='''DragonSnow, LtxProgrammer, bijimio, Valurio9683, KoBOLTA, poptartiguess, N1CO785, BaiTian6641, Foxyas, Kedr2806, xxXMinionXxx, Sel7D4, Candnhen, ABTOR, Twix#5803, dahotdogdesant'''
authors="Azurebyss/BNDS-tx, LtxProgrammer"
description='''Gooey transfur mod created by LtxProgrammer, inspired by Dragon Snow's Changed.'''
[[dependencies.changed]]
    modId="forge"
    mandatory=true
    versionRange="[40.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.changed]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
